### ISSUE TITLE
Linux/Mac compatability, process list

### ISSUE THREAD

**Issue by LottieVixen** [tyrope/DVSaveSwitcher#4]
**Describe the bug**
Won't work on linux or mac due to process_exists calling tasklist which doesn't exist on either systems

**To Reproduce**
run `python DVSaveSwitcher.py`

**Expected behavior**
get the process list another way on linux or bypass the check and just warn the user that the game should be closed.

**Copy-paste**
```
lottie@roci ~/g/DVSaveSwitcher (master)> python DVSaveSwitcher.py
---------------------------------------------
-- Derail Valley Savegame Switcher v1.0.6  --
-- (c)2020-2021 Dimitri "Tyrope" Molenaars --
--     See LICENSE for more information    --
---------------------------------------------
Loading configuration...
Config file found.
Savegame location: /home/lottie/steam/steam/steamapps/common/Derail\ Valley/DerailValley_Data/SaveGameData
Configuration complete.
Traceback (most recent call last):
  File "/home/lottie/git/DVSaveSwitcher/DVSaveSwitcher.py", line 225, in <module>
    while process_exists('derailValley.exe'):
  File "/home/lottie/git/DVSaveSwitcher/DVSaveSwitcher.py", line 197, in process_exists
    output = subprocess.check_output(call).decode(errors="ignore")
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'TASKLIST'
```

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Python version 3.9.7
 - DVSS Version 1.0.6 / commit b6400bf599cc48137c73789361e8031816df4a52

**Comment by tyrope** [comment]
![image](https://user-images.githubusercontent.com/516490/140532737-b7145512-9736-4c34-9b4d-04fb5a945352.png)

**Comment by tyrope** [comment]
Whilst the game doesn't officially support Max and Linux, and I can't test due to not having those platforms, support and development for those platforms will be up to the community; "Patches welcome", as they say.
